# rm pending_data_memory_pool_storage
# rm pending_data_storage
# rm pending_index_memory_pool_storage
# rm pending_index_storage
# rm pendingnum_data_memory_pool_storage
# rm pendingnum_data_storage
# rm pendingnum_index_memory_pool_storage
# rm pendingnum_index_storage
# rm record_data_memory_pool_storage
# rm record_data_storage
# rm record_index_memory_pool_storage
# rm record_index_storage
# rm recordnum_data_memory_pool_storage
# rm recordnum_data_storage
# rm recordnum_index_memory_pool_storage
# rm recordnum_index_storage
# rm station_data_memory_pool_storage
# rm station_data_storage
# rm station_index_memory_pool_storage
# rm station_index_storage
# rm train_data_memory_pool_storage
# rm train_data_storage
# rm train_index_memory_pool_storage
# rm train_index_storage
# rm user_data_memory_pool_storage
# rm user_data_storage
# rm user_index_memory_pool_storage
# rm user_index_storage
rm -r bin/*